### PR TITLE
Fixes #35, and adds two fixes that were applied to the library directly.

### LINKED ISSUE #35: Missing handling for lack of results from PSI
The script currently fills the row with empty strings, which isn't interpreted as a space when parsing into the slide.

### PR DESCRIPTION
**Pull request by notmariazoe**
Fixes issue #35 by adding N/A to the fields that weren't populated in case of an error from the PSI API. It also highlights this was due to a PSI Error on the subtitle column.

It also includes the following fixes, which were applied to the library:
* Retrieves the TextRange from the Placeholder fields before editing the text.
* Only attempts to fill in a placeholder text *if* said placeholder is defined in the configuration column.

### CODE REVIEW

File: src/sls_facades.js [hunk 1]
```diff
@@ -31,8 +31,7 @@
 /* exported filterAndSortData */
 /* exported colorForCWV */
 
-// Document properties
-const documentProperties = PropertiesService.getDocumentProperties();
+documentProperties = PropertiesService.getDocumentProperties();
```
Comment (adamread) [inline src/sls_facades.js:34]: Not clear why this is no longer declared as const. Can you add a comment specifying where it's declared and why it's being overridden here?

File: src/sls_facades.js [hunk 2]
```diff
@@ -277,46 +275,48 @@ function getFunctionByName(functionName) {
...
-* @return {boolean} Whether the URL is a valid image URL.
-*/
+ * Checks if the given URL is a valid image URL.
+ *
+ * @param {string} url The URL to check.
+ * @return {boolean} Whether the URL is a valid image URL.
+ */
 function isValidImageUrl(url) {
-// TODO: Check if it's an image
+  // TODO: Check if it's an image
```
Comment (adamread) [inline src/sls_facades.js:284]: Best practice is still to tie the TODO to a bug or FR.

**Review by adamread — APPROVED** [review]
I left what I think are two nits, so I won't hold the merge up if you don't think they warrant a change.
